### ISSUE TITLE
[Bug] Wrong resolution value in 'Display' 

### ISSUE THREAD

**Issue by AkariiinMKII** [AkariiinMKII/Windows-screenFetch#3]
`Get-CimInstance -ClassName Win32_VideoController` used in [main branch](https://github.com/AkariiinMKII/Windows-screenFetch/tree/use-native-resolution) will [miss monitors info](https://github.com/AkariiinMKII/Windows-screenFetch/issues/2) when using fewer graphics cards than monitors.

Meanwhile, the command in [another branch](https://github.com/AkariiinMKII/Windows-screenFetch/tree/use-display-resolution) fixed this but uses display resolution instead of native resolution. For example, when using 200% scale on a 4K monitor, you will get `1920 x 1080` in `Display` area.

**Comment by FinnTheHero** [comment]
`Function Get-Displays {
    $displays = @()

    $monitors = Get-CimInstance -Namespace "root\wmi" -Class WmiMonitorListedSupportedSourceModes

    foreach ($monitor in $monitors) {
        $sortedResolutions = $monitor.MonitorSourceModes | Sort-Object -Property { $_.HorizontalActivePixels * $_.VerticalActivePixels }
        $maxResolution = "{0} x {1}" -f $sortedResolutions[-1].HorizontalActivePixels, $sortedResolutions[-1].VerticalActivePixels
        $displays += $maxResolution
    }

    return $displays
}`
I used this in my version of this project and it returns both of my monitors native resolutions as you can see on screenshot
![image](https://github.com/AkariiinMKII/Windows-screenFetch/assets/127041443/0d45e343-7e25-4ad6-bfa8-73088c5291fc)
![image](https://github.com/AkariiinMKII/Windows-screenFetch/assets/127041443/67c1d9b6-8c22-4d60-8070-962582802781)

**Comment by AkariiinMKII** [comment]
> ```
> Function Get-Displays {
>     $displays = @()
> 
>     $monitors = Get-CimInstance -Namespace "root\wmi" -Class WmiMonitorListedSupportedSourceModes
> 
>     foreach ($monitor in $monitors) {
>         $sortedResolutions = $monitor.MonitorSourceModes | Sort-Object -Property { $_.HorizontalActivePixels * $_.VerticalActivePixels }
>         $maxResolution = "{0} x {1}" -f $sortedResolutions[-1].HorizontalActivePixels, $sortedResolutions[-1].VerticalActivePixels
>         $displays += $maxResolution
>     }
>     return $displays
> }
> ```
> 
> I used this in my version of this project and it returns both of my monitors native resolutions as you can see on screenshot
> 
> ![image](https://user-images.githubusercontent.com/127041443/266866250-0d45e343-7e25-4ad6-bfa8-73088c5291fc.png)
> 
> this was maximum scaling percentage I could set
> 
> ![image](https://user-images.githubusercontent.com/127041443/266866286-67c1d9b6-8c22-4d60-8070-962582802781.png)
> 
> Chaning display resolution will not affect it either
> 
> ![image](https://user-images.githubusercontent.com/127041443/266867044-c4e48914-678b-41a3-89b5-1c8f6926315d.png)

It works!
But only on Windows 10... Seems it needs admin privilege on Windows 11
And I put it in [another branch](https://github.com/AkariiinMKII/Windows-screenFetch/tree/use-monitor-descriptor) if you need
![Snipaste_2023-09-11_20-36-19](https://github.com/AkariiinMKII/Windows-screenFetch/assets/6019344/7d1ecba0-65d9-4ae0-bdbc-940a008e2fbf)
![Snipaste_2023-09-11_20-36-04](https://github.com/AkariiinMKII/Windows-screenFetch/assets/6019344/9b716ba5-b2e2-4264-aea5-d95123a426d5)

**Comment by AkariiinMKII** [comment]
@FinnTheHero 
I re-installed Windows 11 on my machine and everything turn out to be ok! I think we have solved this!

**Comment by AkariiinMKII** [comment]
@FinnTheHero 
And finally the cause of permission error I found...LOL
- #8
